/**
 * db-seeder.js — Populates the AQI_DB with reference and time-series data
 *
 * Seed sources (in loading order):
 *   1. parameters       — hardcoded pollutant / met definitions
 *   2. data_sources     — OpenAQ, CPCB, IoT, synthetic registry
 *   3. regions          — India → states → cities
 *   4. stations         — CPCB monitoring stations from cpcb-dataset.js
 *   5. sensors          — IoT sensors from iot-simulator.js
 *   6. calibration_records — synthetic calibration history
 *   7. monthly_aggregates  — CPCB 2019–2023 monthly means
 *   8. measurements     — current state.data (hourly time-series)
 *   9. aqi_readings     — computed from measurements
 *  10. alerts           — auto-generated by DB trigger on AQI insert
 *
 * Depends on: db-engine.js, db-schema.js, cpcb-dataset.js, iot-simulator.js, data.js
 */

const DB_SEEDER = (() => {

  // ── Lookup caches (filled during seed) ─────────────────
  const ID = {
    regions:    {},   // cityId → region_id
    stations:   {},   // stationCode → station_id
    parameters: {},   // code → parameter_id
    sensors:    {},   // `${stationCode}:${paramCode}` → sensor_id
    sources:    {},   // name → source_id
  };

  // ─────────────────────────────────────────────────────────
  // 1. PARAMETERS
  // ─────────────────────────────────────────────────────────
  function seedParameters() {
    const rows = [
      // code, name, full_name, category, unit, mol_wt, who_annual, who_24h, naaqs_annual, naaqs_24h, hard_min, hard_max, description
      ['pm25','PM2.5','Fine Particulate Matter','pollutant','μg/m³',null,5,15,40,60,-0.1,1200,'Particles ≤ 2.5 μm diameter'],
      ['pm10','PM10','Coarse Particulate Matter','pollutant','μg/m³',null,15,45,60,100,-0.1,2000,'Particles ≤ 10 μm diameter'],
      ['no2','NO₂','Nitrogen Dioxide','pollutant','μg/m³',46.005,10,25,40,80,-0.1,600,'Combustion byproduct'],
      ['so2','SO₂','Sulfur Dioxide','pollutant','μg/m³',64.065,40,40,50,80,-0.1,1400,'Fossil fuel combustion'],
      ['o3','O₃','Ozone','pollutant','μg/m³',47.998,60,100,100,180,-0.1,600,'Secondary photochemical pollutant'],
      ['co','CO','Carbon Monoxide','pollutant','mg/m³',28.010,4,null,2,null,-0.1,150,'Incomplete combustion product'],
      ['temperature','Temperature','Ambient Air Temperature','meteorological','°C',null,null,null,null,null,-25,65,'Dry bulb air temperature'],
      ['humidity','Relative Humidity','Relative Humidity','meteorological','%',null,null,null,null,null,0,100,'Water vapour fraction'],
      ['aqi','AQI','Air Quality Index','derived','index',null,null,null,null,null,0,500,'Computed US EPA composite index'],
    ];
    const sql = `INSERT OR IGNORE INTO parameters
      (code,name,full_name,category,standard_unit,molecular_weight,
       who_annual_ugm3,who_24h_ugm3,naaqs_annual_ugm3,naaqs_24h_ugm3,
       hard_min,hard_max,description)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`;
    rows.forEach(r => {
      AQI_DB.run(sql, r);
      ID.parameters[r[0]] = AQI_DB.lastInsertId();
    });
    // Fetch already-existing IDs too
    const { rows: existing } = AQI_DB.query('SELECT code, parameter_id FROM parameters');
    existing.forEach(([code, pid]) => { ID.parameters[code] = pid; });
  }

  // ─────────────────────────────────────────────────────────
  // 2. DATA SOURCES
  // ─────────────────────────────────────────────────────────
  function seedDataSources() {
    const rows = [
      ['CPCB Annual Reports','cpcb_report','CPCB India',null,1,0,null,0,null,100,'Published PDF reports 2019–2023'],
      ['WAQI (aqicn.org)','api','WAQI / aqicn.org','https://api.waqi.info',1,1,null,0,null,87.4,'Real-time US-EPA AQI, browser-direct (needs WAQI token in localStorage.waqi_token)'],
      ['IoT Sensor Network','iot_stream','Internal',null,1,0,null,0,12,95.2,'Simulated low-cost IoT sensor mesh'],
      ['Synthetic Generator','derived','Internal',null,1,0,null,0,0,100,'Seeded PRNG simulation for demo'],
    ];
    const sql = `INSERT OR IGNORE INTO data_sources
      (name,source_type,provider,url,is_active,auth_required,last_fetch_at,
       records_fetched,avg_latency_ms,reliability_pct,notes)
      VALUES (?,?,?,?,?,?,?,?,?,?,?)`;
    rows.forEach(r => {
      AQI_DB.run(sql, r);
      ID.sources[r[0]] = AQI_DB.lastInsertId();
    });
    const { rows: ex } = AQI_DB.query('SELECT name, source_id FROM data_sources');
    ex.forEach(([name, sid]) => { ID.sources[name] = sid; });
  }

  // ─────────────────────────────────────────────────────────
  // 3. REGIONS  (India → 9 states → 10 cities)
  // ─────────────────────────────────────────────────────────
  function seedRegions() {
    AQI_DB.run(`INSERT OR IGNORE INTO regions (name,region_type,parent_id,iso_code,lat,lng,population)
                VALUES ('India','country',NULL,'IN',20.5937,78.9629,1428000000)`);
    const indiaId = AQI_DB.lastInsertId() ||
      AQI_DB.query("SELECT region_id FROM regions WHERE iso_code='IN'").rows[0]?.[0];

    const states = [
      ['Delhi NCR','state','IN-DL',28.7041,77.1025,20667656],
      ['Maharashtra','state','IN-MH',19.7515,75.7139,124904071],
      ['Karnataka','state','IN-KA',15.3173,75.7139,67562686],
      ['West Bengal','state','IN-WB',22.9868,87.855,99609303],
      ['Tamil Nadu','state','IN-TN',11.1271,78.6569,77841267],
      ['Telangana','state','IN-TG',18.1124,79.0193,38467887],
      ['Rajasthan','state','IN-RJ',27.0238,74.2179,81032689],
      ['Uttar Pradesh','state','IN-UP',26.8467,80.9462,237882725],
      ['Gujarat','state','IN-GJ',22.2587,71.1924,71507000],
    ];
    const stateIds = {};
    states.forEach(([name,type,iso,lat,lng,pop]) => {
      AQI_DB.run(`INSERT OR IGNORE INTO regions (name,region_type,parent_id,iso_code,lat,lng,population)
                  VALUES (?,?,?,?,?,?,?)`, [name,type,indiaId,iso,lat,lng,pop]);
      const sid = AQI_DB.lastInsertId() ||
        AQI_DB.query(`SELECT region_id FROM regions WHERE iso_code=?`,[iso]).rows[0]?.[0];
      stateIds[name] = sid;
    });

    const cities = [
      { id:'delhi',     name:'Delhi',     state:'Delhi NCR',   lat:28.6139, lng:77.2090, pop:32065760 },
      { id:'mumbai',    name:'Mumbai',    state:'Maharashtra', lat:19.0760, lng:72.8777, pop:21297000 },
      { id:'bangalore', name:'Bangalore', state:'Karnataka',   lat:12.9716, lng:77.5946, pop:13608066 },
      { id:'kolkata',   name:'Kolkata',   state:'West Bengal', lat:22.5726, lng:88.3639, pop:15134000 },
      { id:'chennai',   name:'Chennai',   state:'Tamil Nadu',  lat:13.0827, lng:80.2707, pop:11235018 },
      { id:'hyderabad', name:'Hyderabad', state:'Telangana',   lat:17.3850, lng:78.4867, pop:10534418 },
      { id:'pune',      name:'Pune',      state:'Maharashtra',    lat:18.5204, lng:73.8567, pop:6629350  },
      { id:'jaipur',    name:'Jaipur',    state:'Rajasthan',      lat:26.9124, lng:75.7873, pop:3909000  },
      { id:'lucknow',   name:'Lucknow',   state:'Uttar Pradesh',  lat:26.8467, lng:80.9462, pop:3500000  },
      { id:'ahmedabad', name:'Ahmedabad', state:'Gujarat',        lat:23.0225, lng:72.5714, pop:8450000  },
    ];
    cities.forEach(c => {
      AQI_DB.run(`INSERT OR IGNORE INTO regions (name,region_type,parent_id,lat,lng,population)
                  VALUES (?,?,?,?,?,?)`,
        [c.name, 'city', stateIds[c.state], c.lat, c.lng, c.pop]);
      const rid = AQI_DB.lastInsertId() ||
        AQI_DB.query(`SELECT region_id FROM regions WHERE name=? AND region_type='city'`,[c.name]).rows[0]?.[0];
      ID.regions[c.id] = rid;
    });
  }

  // ─────────────────────────────────────────────────────────
  // 4. STATIONS  (from CPCB_STATIONS)
  // ─────────────────────────────────────────────────────────
  function seedStations() {
    if (!window.getCPCBStations) return;
    const cityKeys = Object.keys(window.CITIES || {});
    cityKeys.forEach(cityId => {
      const stns = getCPCBStations(cityId);
      const regionId = ID.regions[cityId];
      if (!regionId) return;
      stns.forEach(st => {
        AQI_DB.run(`INSERT OR IGNORE INTO stations
          (region_id, station_code, name, station_type, zone_type, operator, lat, lng, is_active, installed_at)
          VALUES (?,?,?,?,?,?,?,?,?,?)`,
          [regionId, st.id, st.name, 'reference', st.zone?.toLowerCase().replace(/\//g,'_'), 'CPCB', st.lat, st.lng, 1, '2010-01-01']);
        const stnId = AQI_DB.lastInsertId() ||
          AQI_DB.query(`SELECT station_id FROM stations WHERE station_code=?`,[st.id]).rows[0]?.[0];
        if (stnId) ID.stations[st.id] = stnId;
      });
    });

    // Add IoT stations
    if (!window.IOT_NETWORK) return;
    Object.entries(window.IOT_NETWORK).forEach(([cityId, nodes]) => {
      const regionId = ID.regions[cityId];
      if (!regionId) return;
      nodes.forEach(node => {
        const code = node.id;
        AQI_DB.run(`INSERT OR IGNORE INTO stations
          (region_id, station_code, name, station_type, zone_type, operator, lat, lng, is_active, installed_at)
          VALUES (?,?,?,?,?,?,?,?,?,?)`,
          [regionId, code, node.name, 'low_cost', node.zone?.toLowerCase(), 'Internal', node.lat, node.lng, 1, '2022-01-01']);
        const stnId = AQI_DB.lastInsertId() ||
          AQI_DB.query(`SELECT station_id FROM stations WHERE station_code=?`,[code]).rows[0]?.[0];
        if (stnId) ID.stations[code] = stnId;
      });
    });
  }

  // ─────────────────────────────────────────────────────────
  // 5. SENSORS
  // ─────────────────────────────────────────────────────────
  function seedSensors() {
    if (!window.IOT_NETWORK || !window.SENSOR_MODELS) return;
    const MODELS = window.SENSOR_MODELS;
    const paramMap = {
      pm25: ['Plantower PMS7003','optical'],
      pm10: ['Alphasense OPC-N3','optical'],
      no2:  ['Alphasense NO2-B43F','electrochemical'],
      so2:  ['Alphasense SO2-B4','electrochemical'],
      o3:   ['2B Technologies 202','uv_photometry'],
      co:   ['Alphasense CO-B4','electrochemical'],
      temperature: ['Bosch BME680',''],
      humidity:    ['Bosch BME680',''],
    };

    Object.entries(window.IOT_NETWORK).forEach(([cityId, nodes]) => {
      nodes.forEach(node => {
        const stnId = ID.stations[node.id];
        if (!stnId) return;
        Object.entries(paramMap).forEach(([param, [model, tech]]) => {
          const pid = ID.parameters[param];
          if (!pid) return;
          const mdata = MODELS[model] || {};
          const calDate = new Date(Date.now() - 60*24*3600000).toISOString().slice(0,10);
          const nextCal = new Date(Date.now() + 120*24*3600000).toISOString().slice(0,10);
          AQI_DB.run(`INSERT OR IGNORE INTO sensors
            (station_id, parameter_id, sensor_code, model, manufacturer,
             measurement_tech, accuracy_pct, detection_limit,
             installed_at, last_calibration, next_calibration, is_active)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,
            [stnId, pid, `${node.id}:${param}`, model, model.split(' ')[0],
             tech || 'optical', 85 + Math.random()*10, mdata.pm25_noise ?? 1,
             '2022-01-01', calDate, nextCal, 1]);
          const snId = AQI_DB.lastInsertId();
          if (snId) ID.sensors[`${node.id}:${param}`] = snId;

          // Insert a calibration record
          if (snId) {
            AQI_DB.run(`INSERT OR IGNORE INTO calibration_records
              (sensor_id, calibration_date, next_due_date, cal_type,
               zero_offset, span_factor, r_squared, passed)
              VALUES (?,?,?,'field',?,?,?,1)`,
              [snId, calDate, nextCal,
               +(Math.random()*0.5 - 0.25).toFixed(3),
               +(0.95 + Math.random()*0.08).toFixed(4),
               +(0.96 + Math.random()*0.03).toFixed(4)]);
          }
        });
      });
    });
  }

  // ─────────────────────────────────────────────────────────
  // 6. MONTHLY AGGREGATES  (CPCB 2019–2023)
  // ─────────────────────────────────────────────────────────
  function seedMonthlyAggregates() {
    if (!window.CPCB_MONTHLY || !window.CPCB_STATIONS) return;
    const sourceId  = ID.sources['CPCB Annual Reports'];
    const paramKeys = ['pm25','pm10','no2','so2','o3','co','temperature','humidity'];

    Object.entries(window.CPCB_MONTHLY).forEach(([cityId, cityData]) => {
      // Use the first CPCB station as the representative station for monthly data
      const stns = window.getCPCBStations?.(cityId) || [];
      const repStn = stns[0];
      if (!repStn) return;
      const stnId = ID.stations[repStn.id];
      if (!stnId) return;

      paramKeys.forEach(param => {
        const pid = ID.parameters[param];
        if (!pid) return;
        const yearData = cityData[param];
        if (!yearData) return;

        Object.entries(yearData).forEach(([year, months]) => {
          months.forEach((mean, mi) => {
            if (mean == null) return;
            const month = mi + 1;
            // Rough WHO/NAAQS exceedance estimate from monthly mean
            const whoLimit   = (window.WHO_GUIDELINES  || {})[param];
            const naaqsLimit = (window.NAAQS_STANDARDS || {})[param];
            const fraction = (mean / (whoLimit   || Infinity));
            const daysWHO   = whoLimit   ? Math.round(Math.min(28, Math.max(0, (fraction - 1) * 20))) : 0;
            const daysNAAQS = naaqsLimit ? Math.round(Math.min(28, Math.max(0, (mean/naaqsLimit - 1)*12))) : 0;

            AQI_DB.run(`INSERT OR IGNORE INTO monthly_aggregates
              (station_id,parameter_id,year,month,mean_value,min_value,max_value,
               record_count,valid_count,days_exceeding_who,days_exceeding_naaqs,source)
              VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,
              [stnId, pid, +year, month, mean,
               +(mean * 0.6).toFixed(2), +(mean * 1.5).toFixed(2),
               28 * 24, 28 * 22,
               daysWHO, daysNAAQS, 'cpcb']);
          });
        });
      });
    });
  }

  // ─────────────────────────────────────────────────────────
  // 7. MEASUREMENTS  (from current state.data)
  // ─────────────────────────────────────────────────────────
  function seedMeasurements(timeSeriesData, cityId) {
    if (!timeSeriesData?.length || !cityId) return 0;
    const stnCodes = Object.keys(ID.stations).filter(k => k.startsWith(cityId.toUpperCase().slice(0,2)));
    // Find first matching station
    const allStns  = AQI_DB.query(
      `SELECT s.station_id, s.station_code FROM stations s
       JOIN regions r ON s.region_id = r.region_id
       WHERE lower(r.name) = lower(?)`, [cityId]
    ).rows;
    if (!allStns.length) return 0;
    const stnId    = allStns[0][0];
    const sourceId = ID.sources['Synthetic Generator'] ||
                     AQI_DB.query("SELECT source_id FROM data_sources WHERE name='Synthetic Generator'").rows[0]?.[0];

    const params = ['pm25','pm10','no2','so2','o3','co','temperature','humidity','aqi'];
    const insertRows = [];

    timeSeriesData.forEach(dp => {
      const ts = new Date(dp.timestamp).toISOString();
      params.forEach(param => {
        const v = dp[param];
        if (v == null || isNaN(v)) return;
        const pid = ID.parameters[param];
        if (!pid) return;
        insertRows.push([stnId, pid, null, sourceId, ts, ts, +v.toFixed(3), +v.toFixed(3), null, 'VALID', 0, 0]);
      });
    });

    const sql = `INSERT OR IGNORE INTO measurements
      (station_id,parameter_id,sensor_id,source_id,timestamp_utc,timestamp_local,
       value,raw_value,unit,quality_flag,is_imputed,is_outlier)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`;

    // Batch in chunks of 500
    const CHUNK = 500;
    for (let i = 0; i < insertRows.length; i += CHUNK) {
      AQI_DB.runBulk(sql, insertRows.slice(i, i + CHUNK));
    }
    return insertRows.length;
  }

  // ─────────────────────────────────────────────────────────
  // 8. AQI READINGS  (computed from measurements)
  // ─────────────────────────────────────────────────────────
  function seedAQIReadings(timeSeriesData, cityId) {
    if (!timeSeriesData?.length || !cityId) return 0;
    const allStns = AQI_DB.query(
      `SELECT s.station_id FROM stations s
       JOIN regions r ON s.region_id = r.region_id
       WHERE lower(r.name) = lower(?)`, [cityId]
    ).rows;
    if (!allStns.length) return 0;
    const stnId = allStns[0][0];

    const sql = `INSERT OR IGNORE INTO aqi_readings
      (station_id,timestamp_utc,aqi_value,aqi_category,dominant_pollutant,
       pm25_sub_index,pm10_sub_index,no2_sub_index,so2_sub_index,o3_sub_index,co_sub_index,calc_method)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,'us_epa')`;

    const rows = timeSeriesData.map(dp => {
      const ts  = new Date(dp.timestamp).toISOString();
      const cat = window.getAQICategory ? getAQICategory(dp.aqi || 0) : { label: 'Moderate' };
      return [stnId, ts,
        Math.round(dp.aqi || 0),
        cat.label,
        'pm25',
        Math.min(500, Math.round((dp.pm25 || 0) * 1.5)),
        Math.min(500, Math.round((dp.pm10 || 0) * 0.9)),
        Math.min(500, Math.round((dp.no2  || 0) * 2.1)),
        Math.min(500, Math.round((dp.so2  || 0) * 1.8)),
        Math.min(500, Math.round((dp.o3   || 0) * 1.2)),
        Math.min(500, Math.round((dp.co   || 0) * 80)),
      ];
    });

    const CHUNK = 500;
    for (let i = 0; i < rows.length; i += CHUNK) {
      AQI_DB.runBulk(sql, rows.slice(i, i + CHUNK));
    }
    return rows.length;
  }

  // ─────────────────────────────────────────────────────────
  // 9. PIPELINE RUN RECORD  (from pipeline results)
  // ─────────────────────────────────────────────────────────
  function recordPipelineRun(cityId, report) {
    if (!report) return null;
    const regionId = ID.regions[cityId];
    AQI_DB.run(`INSERT INTO pipeline_runs
      (city_id, started_at, finished_at, config_json,
       total_records, issues_found, issues_fixed,
       quality_before, quality_after, duration_ms, status)
      VALUES (?,?,?,?,?,?,?,?,?,?,'completed')`,
      [regionId,
       report.startedAt   || new Date().toISOString(),
       report.finishedAt  || new Date().toISOString(),
       JSON.stringify(report.config || {}),
       report.totalRecords || 0,
       report.issuesFound  || (report.byType ? Object.values(report.byType).reduce((a,b)=>a+b,0) : 0),
       report.totalChanges || 0,
       report.qualityBefore?.overall || null,
       report.qualityAfter?.overall  || null,
       report.duration || 0,
      ]);
    const runId = AQI_DB.lastInsertId();

    // Bulk-insert quality_log entries
    if (report.auditLog?.length && runId) {
      const logRows = report.auditLog
        .filter(e => e.type !== 'summary' && e.param)
        .slice(0, 5000)
        .map(e => {
          const paramId = ID.parameters[e.param];
          return [runId, null, paramId,
            null,
            e.timestamp ? new Date(e.timestamp).toISOString() : null,
            e.type,
            e.before != null ? +e.before : null,
            e.after  != null ? +e.after  : null,
            e.strategy || e.method || null,
          ];
        });
      if (logRows.length) {
        AQI_DB.runBulk(`INSERT INTO quality_log
          (run_id,station_id,parameter_id,measurement_id,timestamp_utc,
           issue_type,original_value,corrected_value,correction_method)
          VALUES (?,?,?,?,?,?,?,?,?)`, logRows);
      }
    }
    return runId;
  }

  // ─────────────────────────────────────────────────────────
  // MAIN: seedAll
  // ─────────────────────────────────────────────────────────
  async function seedAll(options = {}) {
    const { cityId = 'delhi', timeSeriesData = [], pipelineReport = null } = options;
    const t0 = performance.now();
    const log = [];

    try {
      seedParameters();   log.push('✓ parameters');
      seedDataSources();  log.push('✓ data_sources');
      seedRegions();      log.push('✓ regions');
      seedStations();     log.push('✓ stations');
      seedSensors();      log.push('✓ sensors + calibration_records');
      seedMonthlyAggregates(); log.push('✓ monthly_aggregates');

      if (timeSeriesData.length) {
        const mCount = seedMeasurements(timeSeriesData, cityId);
        const aCount = seedAQIReadings(timeSeriesData, cityId);
        log.push(`✓ measurements (${mCount} rows)`);
        log.push(`✓ aqi_readings (${aCount} rows) — alerts auto-generated via trigger`);
      }

      if (pipelineReport) {
        recordPipelineRun(cityId, pipelineReport);
        log.push('✓ pipeline_runs + quality_log');
      }

    } catch (e) {
      log.push(`✗ Error: ${e.message}`);
      console.error('[DB_SEEDER]', e);
    }

    const ms = Math.round(performance.now() - t0);
    log.push(`\nTotal: ${ms} ms`);
    return { log, ms, idMap: ID };
  }

  return { seedAll, recordPipelineRun, ID };

})();

window.DB_SEEDER = DB_SEEDER;
